In [1]:
import imageio
import numpy as np

In [57]:
def rbf_kernel(X):
    sigma_s = -0.02
    sigma_c = -0.02
    W = np.zeros((10000,10000))
    for i in range(10000):
        x1 = i//100
        y1 = i%100
        for j in range(i+1,10000):
            x2 = j//100
            y2 = j%100
            w = np.exp(sigma_s*((x1-x2)**2+(y1-y2)**2))*np.exp(sigma_c*(np.linalg.norm(im2[x1,y1]-im2[x2,y2])**2))
            W[i,j] = W[j,i] = w
    return W

In [37]:
im = imageio.imread('image1.png').astype('float32')
im2 = imageio.imread('image2.png').astype('float32')

In [38]:
im2

Array([[[206., 204., 225.],
        [207., 209., 231.],
        [208., 214., 238.],
        ...,
        [ 40.,  46.,  30.],
        [103., 104.,  70.],
        [ 38.,  32.,  26.]],

       [[213., 211., 232.],
        [209., 214., 234.],
        [206., 217., 239.],
        ...,
        [161., 171., 150.],
        [141., 143., 113.],
        [116., 126., 113.]],

       [[212., 215., 234.],
        [210., 216., 238.],
        [210., 221., 243.],
        ...,
        [107., 105.,  83.],
        [ 34.,  43.,  24.],
        [186., 203., 185.]],

       ...,

       [[160., 147., 130.],
        [167., 156., 138.],
        [161., 149., 133.],
        ...,
        [110., 119., 110.],
        [ 86.,  91.,  35.],
        [ 58.,  65.,   8.]],

       [[183., 172., 154.],
        [171., 159., 143.],
        [167., 155., 139.],
        ...,
        [ 76.,  78.,  71.],
        [139., 145., 103.],
        [112., 129.,  47.]],

       [[171., 160., 142.],
        [172., 161., 143.],
        [166., 1

In [58]:
W1 = rbf_kernel(im)
W1

array([[0.00000000e+000, 2.83654042e-001, 3.92652902e-003, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [2.83654042e-001, 0.00000000e+000, 2.18711854e-001, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [3.92652902e-003, 2.18711854e-001, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       ...,
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 1.73056346e-158, 2.20295092e-027],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        1.73056346e-158, 0.00000000e+000, 1.44827233e-151],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        2.20295092e-027, 1.44827233e-151, 0.00000000e+000]])

In [59]:
W2 = rbf_kernel(im2)
W2

array([[0.00000000e+000, 2.83654042e-001, 3.92652902e-003, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [2.83654042e-001, 0.00000000e+000, 2.18711854e-001, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [3.92652902e-003, 2.18711854e-001, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       ...,
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 1.73056346e-158, 2.20295092e-027],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        1.73056346e-158, 0.00000000e+000, 1.44827233e-151],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        2.20295092e-027, 1.44827233e-151, 0.00000000e+000]])

In [71]:
-0.02*((0-99)**2+(0-99)**2)

-392.04